
###
POST http://localhost:5000/account/login HTTP/1.1
Content-Type: application/json

{
    "email_or_phone": "admin@gmail.com",
    "code": "000000"
}


###
GET http://localhost:5000/account/readBag HTTP/1.1
Content-Type: application/json

###
POST http://localhost:5000/account/pushBag HTTP/1.1
Content-Type: application/json

{
    "_id": "62a95e2bd566f89d33c6621e",
    "color": "Red",
    "quantity": 20
}

###
POST http://localhost:5000/account/updateBag HTTP/1.1
Content-Type: application/json

{
    "bag": [
        {"product": "62a95e2bd566f89d33c6621e", "color": "Red", "quantity": 2}
    ] 
}

###
POST http://localhost:5000/account/signUp HTTP/1.1
Content-Type: application/json

{
    "email_or_phone": "sale@gmail.com",
    "password": "ad1811007491",
    "code": "000000",
    "name": "Saler Account",
    "birth": "2000-12-13T00:00:00.000Z",
    "gender": true,
    "address": {
        "province": "TP HCM",
        "district": "TP Thủ Đức",
        "address": "1 Võ Văn Ngân"
    }
}

###
POST http://adstoresv.herokuapp.com/account/otp HTTP/1.1
Content-Type: application/json

{
    "email_or_phone": "84923202850"
}

###
GET http://adstoresv.herokuapp.com/account/info HTTP/1.1

###
GET http://localhost:5000/account/surface HTTP/1.1

###
POST http://localhost:5000/account/updateInfo HTTP/1.1
Content-Type: application/json 

{
    "name": "Nguyen Khoa Danh",
    "birth": "2000-12-13T00:00:00.000Z",
    "gender": true,
    "address": {
        "province": "TP HCM",
        "district": "Q10",
        "address": "66 Vĩnh Viễn"
    }
}

###
POST http://adstoresv.herokuapp.com/account/updatePhone HTTP/1.1
Content-Type: application/json 

{
    "phone": "+84923202850",
    "code": "000000"
}

###
POST http://localhost:5000/account/updatePassword HTTP/1.1
Content-Type: application/json 

{
    "old_password": "ad18110074911",
    "password": "ad1811007491"
}

###
POST http://localhost:5000/account/sendNotification HTTP/1.1
Content-Type: application/json 

{
    "dest_id": "62a4d421426a928106185839",
    "message": "test notification"
}

###
POST http://localhost:5000/account/deleteNotification HTTP/1.1
Content-Type: application/json 

{
    "_id": "62a4dd506f5829a26a2d5cd9"
}

