###
POST http://localhost:5000/statistical/imports HTTP/1.1
Content-Type: application/json


###
POST http://localhost:5000/check_ship HTTP/1.1
Content-Type: application/json

{
    "address": {
        "province": "Hà nội",
        "district": "Quận Cầu Giấy",
        "address": "P.503 tòa nhà Auu Việt, số 1 Lê Đức Thọ"
    }
}

###

GET https://services.giaohangtietkiem.vn/services/shipment/fee?address=P.503%20t%C3%B2a%20nh%C3%A0%20Auu%20Vi%E1%BB%87t,%20s%E1%BB%91%201%20L%C3%AA%20%C4%90%E1%BB%A9c%20Th%E1%BB%8D&province=H%C3%A0%20n%E1%BB%99i&district=Qu%E1%BA%ADn%20C%E1%BA%A7u%20Gi%E1%BA%A5y&pick_province=H%C3%A0%20N%E1%BB%99i&pick_district=Qu%E1%BA%ADn%20Hai%20B%C3%A0%20Tr%C6%B0ng&weight=1000&value=3000000&deliver_option=xteam&tags%5B%5D=1 HTTP/1.1
Token: D505c0ea6e2A953F79b46a5d3A8E37e180EB0827