POST http://localhost:5000/bill/billCalc HTTP/1.1
Content-Type: application/json

{
    "address":{"province":"TP HCM","district":"TP THU DUC","address":"1 VO VAN NGAN"},
    "phone": "84923202850",
    "cod": false
}

###
POST http://localhost:5000/account/login HTTP/1.1
Content-Type: application/json

{
    "email_or_phone": "dannk1312@gmail.com",
    "password": "nkD18110091"
}
