POST http://localhost:5000/bill/create HTTP/1.1
Content-Type: application/json

{
    "bag":[{"product":"62ad8b2404b1746fa859636d","quantity":1,"color":"blue"},{"product":"62ad8b7f04b1746fa8596378","quantity":1,"color":"white"}],
    "phone":"+84919758027",
    "name":"Anh Đỗ Đức",
    "discountCode":"",
    "address":{"province":"TP.HCM","district":"Quận 2","address":"1 Võ Văn Ngân"},"cod":true}
####
POST http://localhost:5000/bill/list HTTP/1.1
Content-Type: application/json

{
    "search": "849446"
}

####
POST http://localhost:5000/bill/verify HTTP/1.1
Content-Type: application/json

{
    "_id": "62bdf7ae5bd5cb6cff78d534"
}

####
POST http://localhost:5000/bill/read HTTP/1.1
Content-Type: application/json

{
    "_id": "62b2904685c7f760bfef00a8"
}




####
POST http://localhost:5000/product/imports HTTP/1.1
Content-Type: application/json

{"data":[{"code":"ATD15","color":"Đen","quantity":20,"price":20000000}]}


###
POST http://localhost:5000/account/login HTTP/1.1
Content-Type: application/json

{
    "email_or_phone": "admin01@gmail.com",
    "code": "000000"
}

###
POST http://localhost:5000/check_ship HTTP/1.1
Content-Type: application/json

{
    "address": {
        "province": "TP.HCM",
        "district": "Quận 2",
        "address": "DVB"
    }
}