
###
POST http://localhost:5000/account/login HTTP/1.1
Content-Type: application/json

{
    "email_or_phone": "adstore7491@gmail.com",
    "password": "ad1811007491"
}


###
POST http://localhost:5000/account/login HTTP/1.1
Content-Type: application/json

{
    "email_or_phone": "dannk1312@gmail.com",
    "code": "000000"
}

###
POST http://localhost:5000/chat/new HTTP/1.1
Content-Type: application/json

{
    "message": "alo"
}

###
GET http://localhost:5000/chat/list HTTP/1.1
Content-Type: application/json


###
POST http://localhost:5000/chat/addMessage HTTP/1.1
Content-Type: application/json

{
    "_id": "62b03c4ae515254e2e87037a",
    "message": "alooo"
}

###
POST http://localhost:5000/chat/getMessages HTTP/1.1
Content-Type: application/json

{
    "_id": "62b03c4ae515254e2e87037a",
    "skip": 0,
    "limit": 2
}



