POST http://localhost:5000/discount/create HTTP/1.1
Content-Type: application/json

{
    "code": "35252",
    "value": "5000"
}
###

POST http://localhost:5000/discount/update HTTP/1.1
Content-Type: application/json

{
    "code": "35252",
    "enable": true
}


###
POST http://adstoresv.herokuapp.com/discount/list HTTP/1.1
Content-Type: application/json
