POST http://localhost:5000/default/emailOTP HTTP/1.1
content-type: application/json

{
    "email": "doducanh0312@gmail.com"
}

####
POST http://localhost:5000/default/createByMail HTTP/1.1
content-type: application/json

{
    "email": "sandais2903@gmail.com",
    "password": "sD123456",
    "code": "569803"
}

####
POST http://localhost:5000/default/login HTTP/1.1
content-type: application/json

{
    "email_or_phone": "dannk1312@gmail.com",
    "password": "nkD18110091"
}

####
POST http://localhost:5000/default/login HTTP/1.1
content-type: application/json

{
    "email_or_phone": "sandais2903@gmail.com",
    "password": "sD123456"
}

####
POST http://localhost:5000/chat/newChat HTTP/1.1
content-type: application/json

{
    "message": "Alo2"
}

####
POST http://localhost:5000/chat/addChatMessage HTTP/1.1
content-type: application/json

{
    "chatId": "62691e6e7fd95aacf7114ebc",
    "message": "Ô cc? chỗ tôi không bán ô tô"
}

####
POST http://localhost:5000/chat/getChat HTTP/1.1
content-type: application/json

{
    "chatId": "62691e6e7fd95aacf7114ebc",
    "index": 4,
    "length": 2
}