POST http://localhost:5000/customer/updateInfo HTTP/1.1
content-type: application/json

{
    "name": "Nguyen Khoa Danh", 
    "birth": "12/13/2000", 
    "gender": "Male", 
    "address": ["Baria", "TPHCM"]
}

####
POST http://localhost:5000/customer/login HTTP/1.1
content-type: application/json

{
    "email": "dannk1312@gmail.com",
    "password": "nkD18110091"
}


####
POST http://localhost:5000/customer/phoneOTP HTTP/1.1
content-type: application/json

{
    "phone": "+84923202851"
}

####
POST http://localhost:5000/customer/updatePhone HTTP/1.1
content-type: application/json

{
    "newPhone": "+84923202851",
    "code": "409024"
}




