POST http://localhost:5000/default/otp HTTP/1.1
content-type: application/json

{
    "email_or_phone": "dannk1312@gmail.com"
}

####
POST http://localhost:5000/default/signUp HTTP/1.1
content-type: application/json

{
    "email_or_phone": "dannk1312@gmail.com",
    "password": "nkD11312",
    "code": "691319"
}

####
POST http://localhost:5000/default/login HTTP/1.1
content-type: application/json

{
    "email_or_phone": "dannk1312@gmail.com",
    "password": "nkD11312"
}

####
GET http://localhost:5000/default/info HTTP/1.1

####
POST http://localhost:5000/default/login HTTP/1.1
content-type: application/json

{
    "email_or_phone": "sandais2903@gmail.com",
    "password": "sD123456"
}

####
POST http://localhost:5000/chat/newChat HTTP/1.1
content-type: application/json

{
    "message": "Alo2"
}

####
POST http://localhost:5000/chat/addChatMessage HTTP/1.1
content-type: application/json

{
    "chatId": "62691e6e7fd95aacf7114ebc",
    "message": "Ô cc? chỗ tôi không bán ô tô"
}

####
POST http://localhost:5000/chat/getChat HTTP/1.1
content-type: application/json

{
    "chatId": "62691e6e7fd95aacf7114ebc",
    "index": 4,
    "length": 2
}

####
POST http://localhost:5000/category/update HTTP/1.1
content-type: application/json

{
    "_id": "629b4768b0d09e4621cef5da",
    "name": "Laptop",
    "specsModel": [{
        "_id": "629bc381695be9a7edb733d4",
        "name": "Ram",
        "values": []
    }]
}

####
POST http://localhost:5000/category/read HTTP/1.1
content-type: application/json

{
    "name": "Laptop"
}

####
GET http://localhost:5000/category/list HTTP/1.1